### ISSUE TITLE
ValidationError: Unsupported data type: object is set for `data` object

### ISSUE THREAD

**Issue by RezaOwliaei** [fogine/couchbase-odm#26]
Hi. I'm trying to create my first model using your getting started guide:

```js
const couchbase = require('../databases/couchbase');
const User = couchbase.define('User', {
    type: 'object',
    properties: {
        username: {type: 'string'},
    }
}, {
    //options
    timestamps: true
});
module.exports = User;
```

This is the output:
```
     ValidationError: Unsupported data type: object is set for `data` object
      at validatePropertyType (/usr/src/node_modules/kouchbase-odm/lib/sanitizer/schema.js:96:15)
      at sanitize (/usr/src/node_modules/kouchbase-odm/lib/sanitizer/schema.js:52:5)
      at Model.sanitizeSchema (/usr/src/node_modules/kouchbase-odm/lib/sanitizer/schema.js:35:5)
      at Model.$init (/usr/src/node_modules/kouchbase-odm/lib/model.js:141:24)
      at CouchbaseODM.define (/usr/src/node_modules/kouchbase-odm/index.js:135:11)
      at Object.<anonymous> (modules/user/models/userModel.js:2:24)
```
__Node version:__ v10.9.0
__CouchbaseODM version/branch:__ 2.0.0-rc.1

Thank you for your help.

**Comment by fogine** [comment]
Hey @RezaOwliaei ,
the documentation describes the most recent version of `kouchbase-odm@3.0.0-alpha` .  
Currently `3.0.0-alpha` is not intentionally tagged with `latest` tag, that's why npm installs `2.0.0-rc.1` by default. 
if you want the documentation for the previous version `2.0.0-rc.1`  you can get it by:  

```bash
> git clone https://github.com/fogine/couchbase-odm.git
> cd couchbase-odm
> git checkout v2.0.0-rc.1
> npm i
> npm run generate-docs
# then it will be available in ./docs/<version>/index.html
```

**Comment by fogine** [comment]
https://fogine.github.io/couchbase-odm/tutorial-8.2.x-to-3.x.html
